# Generated by Django 2.2.4 on 2020-05-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.CharField(default='good show', max_length=255),
            preserve_default=False,
        ),
    ]
